#%RAML 1.0 NamedExample
value:
  productPriceResponses:
    -
      currency: "USD"
      productCode: "123456"
      uom: "EA"
      qty: "10"
      grossPrice: "1000"
      netPrice: "800"
      totalNetPrice: "8000"
      customerDiscount: "20%"
      additionalDiscount: ""
