#%RAML 1.0 NamedExample
value:
  registrationStatus: "PENDING_APPROVAL"
  salutation: "string"
  firstName: "Firstname"
  lastName: "Lastname"
  email: "example@test.com"
  jobTitle: "Job title"
  companyName: "string"
  streetAddress1: "string"
  streetAddress2: "string"
  city: "City"
  country:
    isoCode: "UA"
    name: "Ukraine"
  state: "state"
  telephone: "980-425-8032"
  phoneExtension: "+380"
  zipCode: "04210"
  lastCommerceUpdate: "2016-02-28T16:41:41.090Z"
  bpUnitId: "110491"
